import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { cookies } from "next/headers";
import { SESSION_COOKIE_NAME, verifySessionToken } from "@/src/lib/auth";
import { ProfileMenu } from "@/app/components/profile-menu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const session = verifySessionToken(cookieStore.get(SESSION_COOKIE_NAME)?.value);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[color:var(--background)] text-[color:var(--foreground)]">
        <header className="sticky top-0 z-50 w-full bg-white/70 dark:bg-black/70 backdrop-blur-sm shadow-sm">
          <div className="mx-auto max-w-4xl px-4 py-4 flex items-center justify-between">
            <Link href="/" className="text-lg font-semibold">
              ArtistMeet
            </Link>
            <nav className="relative text-sm text-gray-600 dark:text-gray-300">
              {!session ? (
                <>
                  <Link href="/login" className="px-3 hover:underline">
                    Login
                  </Link>
                  <Link href="/register" className="px-3 hover:underline">
                    Register
                  </Link>
                </>
              ) : (
                <>
                  <ProfileMenu username={session.username} />
                </>
              )}
            </nav>
          </div>
        </header>

        <main className="flex-1">
          <div className="mx-auto max-w-4xl px-4 py-10">{children}</div>
        </main>

        <footer className="w-full border-t border-gray-200 dark:border-gray-800">
          <div className="mx-auto max-w-4xl px-4 py-6 text-center text-sm text-gray-600 dark:text-gray-400">
            © {new Date().getFullYear()} ArtistMeet, All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
